export const actionTypes = {
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  FILTER_PRODUCTS: "FILTER_PRODUCTS",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  USER_LOGIN: "USER_LOGIN",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGOUT: "USER_LOGOUT",
  USER_REGISTER: "USER_REGISTER",
  USER_REGISTER_FAIL: "USER_REGISTER_FAIL",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
};
